install.packages("neuralnet")
library(neuralnet)
input <- as.data.frame(runif(100,min=0,2*pi))
output <- abs(cos(input))^(abs(sin(input)))
trainingdata <-cbind(input,output)
colnames(trainingdata)<-c("Wejœcie","Wyjœcie")
net.sqrt <- neuralnet(Wyjœcie~Wejœcie,trainingdata,hidden=7,threshold=0.01,stepmax=1e7)
print(net.sqrt)
plot(net.sqrt,rep="best")
testdata <- as.data.frame(runif(300,min=0,max=20))
net.results <- compute(net.sqrt, testdata)
print(net.results$net.result)
cleanoutput <- cbind(testdata,log(testdata^2),as.data.frame((net.results$net.result)))
colnames(cleanoutput) <- c("Wejœcie", "Oczekiwane Wyjœcie", "Wyjœcie sieci neuronowej")
print(cleanoutput)